# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015, 2016, 2017 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4

notifications:
  email: false

sudo: false

services:
  - mysql
  - postgresql
  - rabbitmq

language: python

cache:
  - pip

env:
  global:
    - ES2_DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.2/elasticsearch-2.4.2.tar.gz"
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    # ES2 + SQLite
    - REQUIREMENTS=lowest EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
    # ES5 + SQLite
    # Note: SQLite lowest, release, devel are tested above. ES5 lowest, release,
    # devel are tested below for both MySQL and PostgreSQL.
    - REQUIREMENTS=release EXTRAS=all,sqlite,elasticsearch5 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES5_DOWNLOAD_URL
    # ES5 + MySQL
    - REQUIREMENTS=lowest EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
    # ES5 + PostgreSQL
    - REQUIREMENTS=lowest EXTRAS=all,postgresql,elasticsearch5 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,postgresql,elasticsearch5 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES5_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=devel EXTRAS=all,postgresql,elasticsearch5 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES5_DOWNLOAD_URL

python:
  - "2.7"
  - "3.5"

matrix:
  fast_finish: true


before_install:
  - "nvm install 6; nvm use 6"
  - "mkdir /tmp/elasticsearch"
  - "wget -O - ${ES_URL} | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - /tmp/elasticsearch/bin/elasticsearch --version
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "lYM0Rd0yBrJHBxOlA7qU7dx6FxJl8mjeDFipGn5C+sPrs5RRR6S5MJJZLjKhQDNQfsc8zsfe38QiaK/9geOh0mZMSw1kQvJNY/BJZ5PWbUW635470T/bfILj0lM2vlob2WVdsXnudHBPpBVQDCQsfjy1baQVQqa9z9gsobH9J95o5lTDPme7DXuAf6C3HNW0Gq8zs/O3ifpn3eo+PNHZHsGsU95ZW+NlrKHQKZBVOtij9FD6QTX0rbfoAUWG0tkoUA330yNlI/9pGAONlI7yEquQGh4kKZ6KQbQA2UlInsdInU/hgz4gsZ6WuVxV8BIUQYCKzDyl1JOyrvcQJMElA4js0LjIFUUndci1yme74efWKctIKV3okr9zBKCpfytT2cJgApkRuQ+i5H99Os+7aK5kuPf7xP2/ZC/vlh0i/IOJq5Kgy4jSJUkds+Ftjsy0DYSBXZXa/1Zr3dy4PPaXHhh1sj5l/ev74/+aXbpkmMJSCuzD1QfQ6zH2X7PUO+wZ09n+pWAbXVGCiVb4+FBbvSEML/7mu65NJ16wTchCjDFPHyhnL4rvszRWJe51RFnNx3GM/tlBZa1d7GnSoKHy1K08fTHsM02vQ0xgrgu35sdJGid2Wmahuv17im3+CsGGv4jhEkMXKdYPE6XZZBLJRWgXzcFSjbqw5qytkd62a1A="
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-oaiserver
    condition: $DEPLOY = true
